1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

In [20]:
import pandas as pd
df_ventas = pd.read_csv('Archivos/ventas.csv')
df_ventas.head()

,ID_Venta,Fecha,ID_Cliente,ID_Producto,Cantidad,Precio_Unitario,Total,Metodo_Pago
0,1001,2026-03-01,1,PROD-01,2,1200.5,2401.0,Tarjeta de Crédito
1,1002,2026-03-01,2,PROD-03,1,4500.0,4500.0,Efectivo
2,1003,2026-03-02,3,PROD-02,1,850.0,850.0,Transferencia
3,1004,2026-03-02,1,PROD-05,3,3100.0,9300.0,Tarjeta de Crédito
4,1005,2026-03-03,4,PROD-01,1,1200.5,1200.5,Mercado Pago

2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

In [21]:
df_clientes = pd.read_json('Archivos/clientes.json')
df_clientes

,id_cliente,nombre,email,telefono,direccion,categoria,fecha_registro
0,1,Ana Gómez,ana.gomez@example.com,+54 9 11 4567-8901,"{'calle': 'Av. Corrientes 1234', 'ciudad': 'Bu...",VIP,2024-01-15
1,2,Carlos Rodríguez,carlos.rodriguez@example.com,+54 9 351 234-5678,"{'calle': 'Calle San Martín 456', 'ciudad': 'C...",Regular,2024-05-20
2,3,Lucía Fernández,lucia.f@example.com,+54 9 341 876-5432,"{'calle': 'Bulevar Oroño 789', 'ciudad': 'Rosa...",Frecuente,2024-08-10
3,4,Martín Silva,martin.silva@example.com,+54 9 261 345-6789,"{'calle': 'Av. San Martín 1012', 'ciudad': 'Me...",Regular,2025-02-01
4,5,Sofia Martínez,sofia.m@example.com,+54 9 2964 12-3456,"{'calle': 'Av. Belgrano 550', 'ciudad': 'Rio G...",VIP,2025-06-18

In [22]:
df_clientes['id_cliente'].nunique()

5

3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.

In [17]:
df_inventario = pd.read_excel('Archivos/inventario.xlsx')
df_inventario

,ID_Producto,Nombre_Producto,Categoría,Stock_Actual,Stock_Mínimo,Precio_Costo,Precio_Venta,Estado_Stock
0,PROD-01,Teclado Mecánico RGB,Periféricos,45,10,800,1200.5,NaN
1,PROD-02,Mouse Óptico Inalámbrico,Periféricos,8,15,500,850.0,NaN
2,PROD-03,Monitor 24' Full HD,Monitores,12,5,3000,4500.0,NaN
3,PROD-04,Auriculares Bluetooth,Audio,25,10,1400,2100.0,NaN
4,PROD-05,Silla Ergonómica de Oficina,Mobiliario,4,5,2000,3100.0,NaN
5,PROD-06,Webcam 1080p con Micrófono,Accesorios,30,8,1200,1850.0,NaN
6,PROD-07,Disco Rígido Externo 1TB,Almacenamiento,18,10,2500,3800.0,NaN
7,PROD-08,Escritorio Elevable Eléctrico,Mobiliario,2,3,15000,22500.0,NaN

In [23]:
df_inventario["Stock_Actual"].mean()

np.float64(18.0)